spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/icdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xiayanhui
    #password: n6untBcxNv

  mvc:
    favicon:
      enabled: false



mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:/mybaties-mappers/*.xml

Server:
  port: 80